// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1q6ozsMvEkvw0lhpdxzm4TZpjX1bTyk',
    appId: '1:660026182554:web:047b790075a71d55b4c823',
    messagingSenderId: '660026182554',
    projectId: 'kenoverse-8f206',
    authDomain: 'kenoverse-8f206.firebaseapp.com',
    storageBucket: 'kenoverse-8f206.firebasestorage.app',
    measurementId: 'G-WDSFM756KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYEOj7TIBlm-XayJ-lv5NInCu8WgNB3E',
    appId: '1:660026182554:android:1dfdb3c30b49a7b3b4c823',
    messagingSenderId: '660026182554',
    projectId: 'kenoverse-8f206',
    storageBucket: 'kenoverse-8f206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCglAIz9OgCi5JhG0KRm9esUXXYKYIKG1I',
    appId: '1:660026182554:ios:0ca8e66a8337a6c0b4c823',
    messagingSenderId: '660026182554',
    projectId: 'kenoverse-8f206',
    storageBucket: 'kenoverse-8f206.firebasestorage.app',
    iosBundleId: 'com.monarch.kenoverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCglAIz9OgCi5JhG0KRm9esUXXYKYIKG1I',
    appId: '1:660026182554:ios:0ca8e66a8337a6c0b4c823',
    messagingSenderId: '660026182554',
    projectId: 'kenoverse-8f206',
    storageBucket: 'kenoverse-8f206.firebasestorage.app',
    iosBundleId: 'com.monarch.kenoverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1q6ozsMvEkvw0lhpdxzm4TZpjX1bTyk',
    appId: '1:660026182554:web:6fb9863e12852415b4c823',
    messagingSenderId: '660026182554',
    projectId: 'kenoverse-8f206',
    authDomain: 'kenoverse-8f206.firebaseapp.com',
    storageBucket: 'kenoverse-8f206.firebasestorage.app',
    measurementId: 'G-0LZ5825C1E',
  );

}